common: ssh_key: append trailing \n on invalid keys
In production, we found out that some ssh key secrets can be badly
configured in secret managers (such as vault).
In fact, even if there is a missing newline in the key, we can observe
the following error:

Traceback (most recent call last):
  File "/opt/resource/check", line 59, in <module>
    main()
  File "/opt/resource/check", line 55, in main
    print(json.dumps(check(sys.stdin)))
  File "/opt/resource/check", line 36, in check
    common.add_private_key_to_agent(config.private_key)
  File "/opt/resource/repo_resource/common.py", line 41, in add_private_key_to_agent
    raise e
  File "/opt/resource/repo_resource/common.py", line 35, in add_private_key_to_agent
    ssh_agent_setup.add_key(keypath)
  File "/usr/local/lib/python3.10/site-packages/ssh_agent_setup/__init__.py", line 44, in add_key
    raise Exception('failed to add the key: {}'.format(key_file))
Exception: failed to add the key: /tmp/tmpn_m5eddv
failed

This is reproduced with ssh-add as well:
$ ssh-add tmptt1l3j3y
Error loading key "tmptt1l3j3y": invalid format
$ vim tmptt1l3j3y # to add the missing newline
$ ssh-add tmptt1l3j3y
Identity added: tmptt1l3j3y (private-ssh-key)

Make the code more robust by appending a newline whenever there is no
one.
Note that adding multiple newlines does not break "ssh-add".

Signed-off-by: Jonathan Monnet <jmonnet@baylibre.com>
Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>