common: tests: use assertEqual for python-3.12 compatibility
On recent systems with python-3.12, the unit tests fail with a
syntax error:
======================================================================
ERROR: test_get_metadata (repo_resource.test_in.TestIn.test_get_metadata)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/repo_resource/test_in.py", line 85, in test_get_metadata
    self.assertEquals(result['metadata'][0]['name'], expected_project)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'TestIn' object has no attribute 'assertEquals'. Did you mean: 'assertEqual'?

Fix it by using assertEqual instead of assertEquals.

Signed-off-by: Mattijs Korpershoek <mkorpershoek@baylibre.com>